name: ezoic_flutter_sdk
description: Ezoic Ads SDK for Flutter (Prebid + Google Ad Manager banner, native, interstitial and rewarded ads).
version: 1.4.0
homepage: https://github.com/ezoic/flutter-sdk
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ezoic.ezoic_flutter_sdk
        pluginClass: EzoicFlutterSdkPlugin
      ios:
        pluginClass: EzoicFlutterSdkPlugin
